packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@eslint-react/eslint-plugin': ^1.52.2
  '@eslint/config-inspector': ^0.5.4
  '@types/node': ^24.0.10
  eslint: ^9.30.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  react: ^19.1.0
  react-dom: ^19.1.0
  stylelint: ^16.21.0
  typescript: ^5.8.3
